(function(){
'use strict';
var $=function(id){return document.getElementById(id)};
var state={projectId:'project-general',projectName:'—',responseId:'',activeJob:'',busy:false,history:[],claude:false,writes:false,view:'home'};
var E={project:$('projectSelect'),healthDot:$('healthDot'),healthText:$('healthText'),pageTitle:$('pageTitle'),homeProject:$('homeProject'),homeHealth:$('homeHealth'),homeBudget:$('homeBudget'),homeClaude:$('homeClaude'),chat:$('chatList'),form:$('composer'),input:$('messageInput'),send:$('sendBtn'),stop:$('stopBtn'),notice:$('notice'),claude:$('claudeBtn'),settingsClaude:$('settingsClaudeBtn'),developer:$('developerBtn'),files:$('filesList'),integrations:$('integrationsList')};
var titles={home:'Главная',chat:'Чат',files:'Файлы',integrations:'Интеграции',settings:'Настройки'};
function storageKey(name){return name+':'+state.projectId}
function read(key,fallback){try{var v=localStorage.getItem(key);return v===null?fallback:v}catch(e){return fallback}}
function write(key,value){try{localStorage.setItem(key,value)}catch(e){}}
function remove(key){try{localStorage.removeItem(key)}catch(e){}}
function loadPrefs(){state.claude=read('atlas_core_claude','0')==='1';state.writes=read('atlas_core_writes','0')==='1';syncToggles()}
function syncToggles(){
  var ct=state.claude?'Claude: вкл':'Claude: выкл';
  if(E.claude){E.claude.textContent=ct;E.claude.classList.toggle('active',state.claude);E.claude.setAttribute('aria-pressed',state.claude?'true':'false')}
  if(E.settingsClaude){var cb=E.settingsClaude.querySelector('b');if(cb)cb.textContent=state.claude?'вкл':'выкл'}
  if(E.developer){var db=E.developer.querySelector('b');if(db)db.textContent=state.writes?'вкл':'выкл'}
  if(E.homeClaude)E.homeClaude.textContent=state.claude?'включен':'выключен';
}
function notify(text,kind){if(!E.notice)return;E.notice.textContent=text||'';E.notice.className='notice'+(text?' show':'')+(kind?' '+kind:'')}
function setOnline(on){if(E.healthDot)E.healthDot.classList.toggle('on',!!on);if(E.healthText)E.healthText.textContent=on?'online':'offline';if(E.homeHealth)E.homeHealth.textContent=on?'online':'offline'}
function setBusy(on,label){state.busy=!!on;if(E.send)E.send.disabled=state.busy;if(E.input)E.input.disabled=state.busy;if(E.stop)E.stop.classList.toggle('hidden',!state.busy);if(label)notify(label,'')}
function saveChat(){write(storageKey('atlas_chat_history'),JSON.stringify(state.history.slice(-100)));state.responseId?write(storageKey('atlas_response_id'),state.responseId):remove(storageKey('atlas_response_id'));state.activeJob?write(storageKey('atlas_active_job_id'),state.activeJob):remove(storageKey('atlas_active_job_id'))}
function loadChat(){
  var raw=read(storageKey('atlas_chat_history'),'[]');
  try{state.history=JSON.parse(raw)||[]}catch(e){state.history=[]}
  if(!Array.isArray(state.history))state.history=[];
  state.responseId=read(storageKey('atlas_response_id'),'')||'';
  state.activeJob=read(storageKey('atlas_active_job_id'),'')||'';
  renderChat();
}
function appendInline(node,text){
  var s=String(text||''),re=/(\*\*[^*]+\*\*|`[^`]+`)/g,last=0,m;
  while((m=re.exec(s))){if(m.index>last)node.appendChild(document.createTextNode(s.slice(last,m.index)));var token=m[0],el;if(token.slice(0,2)==='**'){el=document.createElement('strong');el.textContent=token.slice(2,-2)}else{el=document.createElement('code');el.textContent=token.slice(1,-1)}node.appendChild(el);last=m.index+token.length}
  if(last<s.length)node.appendChild(document.createTextNode(s.slice(last)));
}
function fillBubble(node,text){
  var lines=String(text||'').replace(/\r/g,'').split('\n'),ul=null;
  lines.forEach(function(raw){var line=raw.trimEnd?raw.trimEnd():raw;var trimmed=line.trim();if(!trimmed){ul=null;return}
    var bullet=/^[-*]\s+(.+)/.exec(trimmed);if(bullet){if(!ul){ul=document.createElement('ul');node.appendChild(ul)}var li=document.createElement('li');appendInline(li,bullet[1]);ul.appendChild(li);return}
    ul=null;var heading=/^#{1,4}\s+(.+)/.exec(trimmed);if(heading){var h=document.createElement('h3');appendInline(h,heading[1]);node.appendChild(h);return}
    var p=document.createElement('p');appendInline(p,line);node.appendChild(p);
  });
}
function renderChat(){if(!E.chat)return;E.chat.textContent='';if(!state.history.length){var empty=document.createElement('div');empty.className='empty';empty.innerHTML='<span class="hero-mark">A</span><h2>Чем заняться?</h2><p>Напиши задачу Atlas.</p>';E.chat.appendChild(empty);return}state.history.forEach(function(m){var row=document.createElement('div');row.className='row '+(m.role==='user'?'user':'assistant');var bubble=document.createElement('div');bubble.className='bubble';fillBubble(bubble,m.text||'');row.appendChild(bubble);E.chat.appendChild(row)});requestAnimationFrame(function(){var c=document.querySelector('.content');if(c)c.scrollTop=c.scrollHeight})}
function push(role,text){state.history.push({role:role,text:String(text||'')});saveChat();renderChat()}
function showView(name){if(!titles[name])name='home';state.view=name;document.querySelectorAll('.view').forEach(function(v){v.classList.toggle('active',v.id==='view-'+name)});document.querySelectorAll('[data-view]').forEach(function(b){b.classList.toggle('active',b.getAttribute('data-view')===name)});if(E.pageTitle)E.pageTitle.textContent=titles[name];if(name==='files')loadFiles();if(name==='integrations')loadIntegrations();if(name==='chat'&&E.input)setTimeout(function(){E.input.focus()},60)}
async function json(url,opt){var options=opt||{};options.credentials='same-origin';options.cache='no-store';var r=await fetch(url,options);var j={};try{j=await r.json()}catch(e){}if(r.status===401){location.replace('/app/login.html?v='+Date.now());throw new Error('Unauthorized')}if(!r.ok)throw new Error(j.detail||j.error||('HTTP '+r.status));return j}
async function checkSession(){try{var j=await json('/app-session?core='+Date.now());if(!j.authenticated){location.replace('/app/login.html?v='+Date.now());return false}return true}catch(e){if(e.message!=='Unauthorized')notify('Не удалось проверить сессию','error');return false}}
async function health(){try{var r=await fetch('/health?core='+Date.now(),{cache:'no-store',credentials:'same-origin'});setOnline(r.ok);return r.ok}catch(e){setOnline(false);return false}}
async function loadProjects(){try{var j=await json('/app-projects?core='+Date.now());var list=Array.isArray(j.projects)?j.projects:[];E.project.textContent='';var preferred=read('atlas_active_project_id','project-general');var found=false;list.forEach(function(p){var id=String(p.id||p.project_id||'');if(!id)return;var o=document.createElement('option');o.value=id;o.textContent=String(p.name||p.title||id);if(id===preferred){o.selected=true;found=true}E.project.appendChild(o)});if(found)state.projectId=preferred;else if(list.length)state.projectId=String(list[0].id||list[0].project_id||'project-general');else state.projectId='project-general';E.project.value=state.projectId;var selected=E.project.options[E.project.selectedIndex];state.projectName=selected?selected.textContent:state.projectId;write('atlas_active_project_id',state.projectId);if(E.homeProject)E.homeProject.textContent=state.projectName;loadChat();if(!state.history.length)await hydrateServerHistory();if(state.activeJob)poll(state.activeJob);return list}catch(e){notify('Проекты: '+e.message,'error');return []}}
async function hydrateServerHistory(){try{var j=await json('/app-projects/'+encodeURIComponent(state.projectId)+'/history?core='+Date.now());var jobs=Array.isArray(j.history)?j.history:[];jobs=jobs.slice().sort(function(a,b){return Number(a.created_at||0)-Number(b.created_at||0)});var h=[];jobs.forEach(function(job){if(job.task)h.push({role:'user',text:String(job.task)});if(job.status==='done'&&job.answer)h.push({role:'assistant',text:String(job.answer)})});if(h.length){state.history=h.slice(-100);for(var i=jobs.length-1;i>=0;i--){if(jobs[i].response_id){state.responseId=String(jobs[i].response_id);break}}saveChat();renderChat()}}catch(e){}
async function loadBudget(){try{var j=await json('/app-budget?core='+Date.now());var spent=Number(j.spent_usd!=null?j.spent_usd:(j.today_spent_usd||j.spent||0));var reserved=Number(j.reserved_usd!=null?j.reserved_usd:(j.today_reserved_usd||j.reserved||0));var limit=Number(j.daily_limit_usd||j.daily_limit||0);E.homeBudget.textContent=limit>0?'$'+spent.toFixed(2)+' + $'+reserved.toFixed(2)+' / $'+limit.toFixed(2):'$'+spent.toFixed(2)}catch(e){E.homeBudget.textContent='—'}}
async function loadFiles(){if(!E.files)return;E.files.innerHTML='<div class="muted">Загрузка…</div>';try{var j=await json('/app-files?project_id='+encodeURIComponent(state.projectId)+'&core='+Date.now());var list=Array.isArray(j.files)?j.files:[];E.files.textContent='';if(!list.length){E.files.innerHTML='<div class="muted">В проекте пока нет файлов.</div>';return}list.forEach(function(f){var row=document.createElement('div');row.className='list-row';var left=document.createElement('span');var strong=document.createElement('strong');strong.textContent=String(f.name||f.filename||f.path||'Файл');var small=document.createElement('small');small.textContent=String(f.media_type||f.type||f.file_id||'');left.appendChild(strong);left.appendChild(small);var badge=document.createElement('span');badge.className='badge';badge.textContent=f.size?String(f.size)+' B':'файл';row.appendChild(left);row.appendChild(badge);E.files.appendChild(row)})}catch(e){E.files.innerHTML='<div class="muted">Ошибка: '+escapeText(e.message)+'</div>'}}
function escapeText(s){return String(s||'').replace(/[&<>]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;'}[c]})}
async function loadIntegrations(){if(!E.integrations)return;E.integrations.innerHTML='<div class="muted">Загрузка…</div>';try{var j=await json('/app-integrations/status?core='+Date.now());var data=j.integrations||j.status||j;var keys=Object.keys(data).filter(function(k){return k!=='ok'&&k!=='checked_at'});E.integrations.textContent='';if(!keys.length){E.integrations.innerHTML='<div class="muted">Статусы интеграций недоступны.</div>';return}keys.forEach(function(k){var v=data[k],connected=false,label='';if(typeof v==='boolean'){connected=v;label=v?'подключено':'не подключено'}else if(v&&typeof v==='object'){connected=v.connected===true||v.ok===true||v.configured===true;label=String(v.status||v.state||(connected?'подключено':'не подключено'))}else{label=String(v);connected=/ok|online|connected|true/i.test(label)}var row=document.createElement('div');row.className='list-row';var left=document.createElement('span');var strong=document.createElement('strong');strong.textContent=k;var small=document.createElement('small');small.textContent=label;left.appendChild(strong);left.appendChild(small);var badge=document.createElement('span');badge.className='badge'+(connected?' ok':'');badge.textContent=connected?'online':'status';row.appendChild(left);row.appendChild(badge);E.integrations.appendChild(row)})}catch(e){E.integrations.innerHTML='<div class="muted">Ошибка: '+escapeText(e.message)+'</div>'}}
function wait(ms){return new Promise(function(resolve){setTimeout(resolve,ms)})}
async function poll(jobId){state.activeJob=jobId;saveChat();setBusy(true,'Atlas думает…');var started=Date.now();try{while(state.activeJob===jobId){if(Date.now()-started>5*60*1000)throw new Error('Задача выполняется слишком долго.');var j=await json('/app-jobs/'+encodeURIComponent(jobId)+'?core='+Date.now());if(j.status==='done'){state.responseId=j.response_id||state.responseId;state.activeJob='';push('assistant',j.answer||'Готово.');notify('Готово','ok');return}if(j.status==='error'||j.status==='failed')throw new Error(j.error||'Ошибка Atlas');if(j.status==='cancelled'){state.activeJob='';push('assistant','Задача остановлена.');notify('Остановлено','');return}await wait(1000)}}catch(e){state.activeJob='';push('assistant',e.message||'Ошибка Atlas');notify(e.message||'Ошибка Atlas','error')}finally{setBusy(false);saveChat()}}
async function send(){var text=(E.input.value||'').trim();if(!text||state.busy)return;showView('chat');push('user',text);E.input.value='';setBusy(true,'Отправляю…');try{var j=await json('/app-jobs',{method:'POST',headers:{'Content-Type':'application/json','Cache-Control':'no-cache'},body:JSON.stringify({task:text,previous_response_id:state.responseId||null,project_id:state.projectId,allow_writes:state.writes,claude_review:state.claude,attachments:[]})});if(!j.job_id)throw new Error('Atlas не вернул ID задачи');state.activeJob=String(j.job_id);saveChat();await poll(state.activeJob)}catch(e){push('assistant',e.message||'Ошибка Atlas');notify(e.message||'Ошибка Atlas','error');setBusy(false)}}
async function stopJob(){if(!state.activeJob)return;var id=state.activeJob;notify('Останавливаю…','');try{await json('/app-jobs/'+encodeURIComponent(id),{method:'DELETE'});state.activeJob='';saveChat();setBusy(false);notify('Задача остановлена','')}catch(e){notify(e.message||'Не удалось остановить','error')}}
function newChat(){state.history=[];state.responseId='';state.activeJob='';saveChat();renderChat();showView('chat');notify('Новый чат создан','ok');setTimeout(function(){E.input.focus()},60)}
function toggleClaude(){state.claude=!state.claude;write('atlas_core_claude',state.claude?'1':'0');syncToggles();notify(state.claude?'Claude будет проверять ответы':'Claude Review выключен','ok')}
function toggleWrites(){state.writes=!state.writes;write('atlas_core_writes',state.writes?'1':'0');syncToggles();notify(state.writes?'Developer Mode включён':'Developer Mode выключен',state.writes?'':'ok')}
async function logout(){try{await fetch('/app-logout',{method:'POST',credentials:'same-origin',cache:'no-store'})}catch(e){}location.replace('/app/login.html?v='+Date.now())}
function bind(){document.querySelectorAll('[data-view]').forEach(function(b){b.addEventListener('click',function(){showView(b.getAttribute('data-view'))})});$('homeAskBtn').addEventListener('click',function(){showView('chat')});$('newChatBtn').addEventListener('click',newChat);E.claude.addEventListener('click',toggleClaude);E.settingsClaude.addEventListener('click',toggleClaude);E.developer.addEventListener('click',toggleWrites);$('refreshFilesBtn').addEventListener('click',loadFiles);$('refreshIntegrationsBtn').addEventListener('click',loadIntegrations);$('logoutBtn').addEventListener('click',logout);$('legacyBtn').addEventListener('click',function(){location.assign('/app/index.html?legacy=1&t='+Date.now())});E.project.addEventListener('change',async function(){saveChat();state.projectId=E.project.value||'project-general';write('atlas_active_project_id',state.projectId);var o=E.project.options[E.project.selectedIndex];state.projectName=o?o.textContent:state.projectId;if(E.homeProject)E.homeProject.textContent=state.projectName;loadChat();if(!state.history.length)await hydrateServerHistory();loadBudget();if(state.view==='files')loadFiles()});E.form.addEventListener('submit',function(ev){ev.preventDefault();send()});E.input.addEventListener('keydown',function(ev){if(ev.key==='Enter'&&!ev.shiftKey){ev.preventDefault();send()}});E.stop.addEventListener('click',stopJob)}
async function boot(){bind();loadPrefs();setOnline(false);if(!await checkSession())return;await Promise.all([health(),loadProjects(),loadBudget()]);setInterval(function(){if(!document.hidden)health()},15000);document.addEventListener('visibilitychange',function(){if(!document.hidden)health()});notify('','')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();