(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n};
const NS='http://www.w3.org/2000/svg';
const PATHS={home:'M3 11.5 12 4l9 7.5V21h-6v-6H9v6H3z',chat:'M5 5h14v10H9l-4 4z',projects:'M3 7h7l2 2h9v11H3z',tools:'M14 5a4 4 0 0 0 5 5l-8.5 8.5a2 2 0 1 1-3-3L16 7a4 4 0 0 0-2-2z',file:'M7 3h7l4 4v14H7zM14 3v5h5',template:'M4 4h7v7H4zM13 4h7v7h-7zM4 13h7v7H4zM13 13h7v7h-7z',link:'M10 13a5 5 0 0 0 7.5.5l2-2a5 5 0 0 0-7-7l-1 1M14 11a5 5 0 0 0-7.5-.5l-2 2a5 5 0 0 0 7 7l1-1',settings:'M12 8.5a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7zM4.9 6.8l2-2 1.7.8 1.1-.5.5-1.9h2.8l.5 1.9 1.1.5 1.7-.8 2 2-.8 1.7.5 1.1 1.9.5v2.8l-1.9.5-.5 1.1.8 1.7-2 2-1.7-.8-1.1.5-.5 1.9H9.2l-.5-1.9-1.1-.5-1.7.8-2-2 .8-1.7-.5-1.1-1.9-.5v-2.8l1.9-.5.5-1.1z',search:'M11 18a7 7 0 1 1 0-14 7 7 0 0 1 0 14zM16 16l5 5',code:'M9 6 3 12l6 6M15 6l6 6-6 6',video:'M4 7.5A2.5 2.5 0 0 1 6.5 5h7A2.5 2.5 0 0 1 16 7.5v9A2.5 2.5 0 0 1 13.5 19h-7A2.5 2.5 0 0 1 4 16.5zM16 10l5-3v10l-5-3',shop:'M5 8h14l-1 11H6L5 8zM8 8a4 4 0 0 1 8 0',doc:'M7 3h7l4 4v14H7zM10 12h5M10 16h5'};
function icon(name){const s=document.createElementNS(NS,'svg');s.setAttribute('viewBox','0 0 24 24');const p=document.createElementNS(NS,'path');p.setAttribute('d',PATHS[name]||name);s.append(p);return s}
function activateTab(name){const tab=$$('.tab-button').find(x=>x.dataset.tab===name);if(tab){tab.click();return true}return false}
function mode(label){return $$('.mode-pill,.mode-chip,.quick-card').find(x=>x.textContent.trim().toLowerCase().includes(label.toLowerCase()))}
function preparePrompt(text,submit=false){const input=$('#messageInput');if(!input)return false;input.value=text;input.dispatchEvent(new Event('input',{bubbles:true}));input.focus();if(submit){const form=$('#composer');if(form?.requestSubmit)form.requestSubmit();else $('#sendBtn')?.click()}return true}
function runMode(label){if(label==='Code Studio'&&window.AtlasCodeStudio?.open)return window.AtlasCodeStudio.open();if(label==='Video Studio'&&window.AtlasVideoStudio?.open)return window.AtlasVideoStudio.open();if(label==='Shopify Studio'&&window.AtlasShopifyStudio?.open)return window.AtlasShopifyStudio.open();if(label==='File Studio'&&window.AtlasStudios?.open)return window.AtlasStudios.open('files');const m=mode(label);if(m){m.click();return}if(label==='File Studio'){$('#fileInput')?.click();return}preparePrompt(label==='Code Studio'?'Работаем в Code Studio: ':label==='Video Studio'?'Работаем в Video Studio: ':'Работаем в Shopify Studio: ')}
function toolCard(kind,title,sub,ico){const b=el('button','dash-tool-card '+kind);b.type='button';const ic=el('span','dash-tool-icon');ic.append(icon(ico));b.append(ic,el('strong','',title),el('small','',sub),el('span','dash-tool-arrow','→'));b.onclick=()=>runMode(title);return b}
function command(text,prompt,submit=false){const b=el('button','dash-command',text);b.type='button';b.onclick=()=>preparePrompt(prompt,submit);return b}
function currentProjectName(){const select=$('#projectSelect');if(select?.selectedOptions?.[0]?.textContent)return select.selectedOptions[0].textContent;return 'AtlasCore'}
function createHeader(){const h=el('div','atlas-dash-head');const left=el('button','atlas-project-switch');left.type='button';left.append(el('span','atlas-project-kicker','Проект'),el('div','atlas-project-name',currentProjectName()));left.onclick=()=>window.AtlasProjectSwitcher?.open?.()||$('#projectSelect')?.focus();const search=el('label','atlas-dash-search');search.append(icon('search'));const inp=el('input');inp.type='search';inp.placeholder='Поиск в проекте...';inp.onkeydown=e=>{if(e.key==='Enter'&&inp.value.trim())preparePrompt('Найди в текущем проекте: '+inp.value.trim(),true)};search.append(inp,el('kbd','','⌘ K'));document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();inp.focus()}});const actions=el('div','atlas-dash-head-actions');const share=el('button','dash-head-btn');share.type='button';share.setAttribute('aria-label','Поделиться');share.append(document.createTextNode('⇧ '),el('span','','Поделиться'));share.onclick=()=>window.AtlasShare?.open?.();const panel=el('button','dash-head-btn icon-only','◫');panel.type='button';panel.setAttribute('aria-label','Показать панель проекта');panel.onclick=()=>window.AtlasRightPanel?.toggle?.();const more=el('button','dash-head-btn icon-only','•••');more.type='button';more.setAttribute('aria-label','Меню Atlas');more.onclick=()=>{};actions.append(share,panel,more);h.append(left,search,actions);return h}
function createTools(){const w=el('div','atlas-tool-strip');w.append(toolCard('code','Code Studio','Код, ревью, исправления','code'),toolCard('video','Video Studio','Сценарии, ролики, промпты','video'),toolCard('shop','Shopify Studio','Товары, темы, автоматизации','shop'),toolCard('file','File Studio','Файлы, документы, анализ','doc'));const add=el('button','dash-tool-card add');add.type='button';add.innerHTML='<div><div class="dash-add-mark">＋</div><small>Добавить<br>инструмент</small></div>';add.onclick=()=>window.AtlasToolsCenter?.open?.()||preparePrompt('Подключи или предложи новый инструмент для Atlas: ');w.append(add);return w}
function loadingRow(text){const row=el('div','dash-live-empty',text);row.setAttribute('aria-live','polite');return row}
function createRight(){const r=el('aside','atlas-dashboard-right');const close=el('button','dash-right-close','×');close.type='button';close.setAttribute('aria-label','Закрыть панель проекта');close.onclick=()=>window.AtlasRightPanel?.close?.();r.append(close);const progress=el('section','dash-widget');progress.append(el('h3','','Прогресс проекта'));const p=el('div','dash-progress');const ring=el('div','progress-ring');ring.style.setProperty('--p','0');ring.innerHTML='<span>—%<small>загрузка…</small></span>';const legend=el('div','progress-legend');legend.innerHTML='<div><span><i></i>Готово</span><b>—</b></div><div><span><i></i>В работе</span><b>—</b></div><div><span><i></i>Осталось</span><b>—</b></div>';p.append(ring,legend);progress.append(p);const next=el('section','dash-widget');next.append(el('h3','','Следующие шаги'));const checks=el('div','dash-checks');checks.append(loadingRow('Загружаю реальные задачи проекта…'));next.append(checks);const plan=command('Смотреть план','Покажи актуальный план текущего проекта: выполнено, в работе, заблокировано, следующие шаги и приоритеты.',true);plan.className='dash-link';next.append(plan);const files=el('section','dash-widget');files.append(el('h3','','Файлы'));const fl=el('div','dash-files');fl.append(loadingRow('Загружаю файлы проекта…'));files.append(fl);const all=el('button','dash-link','Смотреть все файлы');all.type='button';all.onclick=()=>activateTab('files');files.append(all);const quick=el('section','dash-widget');quick.append(el('h3','','Быстрые команды'));const cmds=el('div','dash-commands');cmds.append(command('Сводка проекта','Дай краткую актуальную сводку текущего проекта по реальным данным: готово, в работе, риски и следующий шаг.',true),command('Улучшить текст','Улучши следующий текст, сохранив смысл и стиль: ',false),command('Создать план','Составь актуальный практический план текущего проекта: приоритеты, шаги, блокеры и критерии готовности.',true),command('Найти решения','Найди лучшие варианты решения следующей задачи, сравни их и предложи оптимальный: ',false));quick.append(cmds);r.append(progress,next,files,quick);return r}
function sideButton(label,ico,fn){const b=el('button','dash-side-nav-item');b.type='button';b.append(icon(ico),el('span','',label));b.onclick=fn;return b}
function installSidebarNav(){const sidebar=$('#atlasSidebar');if(!sidebar||$('#dashSideNav'))return;const nav=el('nav','dash-side-nav');nav.id='dashSideNav';nav.append(sideButton('Главная','home',()=>window.AtlasNavState?.home?.()||activateTab('chat')),sideButton('Чат','chat',()=>window.AtlasNavState?.chat?.()||activateTab('chat')),sideButton('Проекты','projects',()=>window.AtlasProjectSwitcher?.open?.()||activateTab('projects')),sideButton('Инструменты','tools',()=>window.AtlasToolsCenter?.open?.()),sideButton('Файлы','file',()=>activateTab('files')),sideButton('Шаблоны','template',()=>window.AtlasTemplates?.open?.()||activateTab('actions')),sideButton('Интеграции','link',()=>window.AtlasIntegrations?.open?.()||activateTab('plugins')),sideButton('Настройки','settings',()=>$('#settingsBtn')?.click()));sidebar.querySelector('.atlas-sidebar-head')?.insertAdjacentElement('afterend',nav)}
function syncProjectName(){const n=$('.atlas-project-name'),s=$('#projectSelect');if(n&&s?.selectedOptions?.[0])n.textContent=s.selectedOptions[0].textContent}
function install(){if($('#atlasDashboard')){installSidebarNav();syncProjectName();return}const app=$('.app-shell'),chat=$('#chatCard'),composer=$('#composerWrap');if(!app||!chat||!composer)return;const dash=el('div','atlas-dashboard');dash.id='atlasDashboard';const main=el('main','atlas-dashboard-main');main.append(createHeader(),createTools(),chat,composer);dash.append(main,createRight());app.append(dash);const panels=$('#workspacePanels');if(panels)main.insertBefore(panels,composer);installSidebarNav();setTimeout(syncProjectName,300)}
function maintain(){install();const main=$('.atlas-dashboard-main'),composer=$('#composerWrap'),panels=$('#workspacePanels');if(main&&composer&&panels&&panels.parentElement!==main)main.insertBefore(panels,composer);syncProjectName()}
new MutationObserver(maintain).observe(document.documentElement,{childList:true,subtree:true});document.addEventListener('change',e=>{if(e.target?.id==='projectSelect')setTimeout(syncProjectName,20)});document.readyState==='loading'?document.addEventListener('DOMContentLoaded',install,{once:true}):install()})();