(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],ACTIVE='atlas_active_project_id',DEFAULT='project-general';
let loading=false;
function project(){return localStorage.getItem(ACTIVE)||DEFAULT}
function projectName(){return $('#projectSelect')?.selectedOptions?.[0]?.textContent?.trim()||$('.atlas-project-name')?.textContent?.trim()||'Текущий проект'}
async function get(url){const r=await fetch(url,{cache:'no-store',credentials:'same-origin'}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.detail||j.error||`HTTP ${r.status}`);return j}
function jobsOf(v){return Array.isArray(v?.history)?v.history:Array.isArray(v?.jobs)?v.jobs:[]}
function filesOf(v){return Array.isArray(v)?v:Array.isArray(v?.files)?v.files:[]}
function schedulesOf(v){return Array.isArray(v)?v:Array.isArray(v?.schedules)?v.schedules:[]}
function state(s){s=String(s||'').toLowerCase();if(['done','success','completed'].includes(s))return'done';if(['running','queued','pending','working'].includes(s))return'working';if(['failed','error','cancelled'].includes(s))return'bad';return'plan'}
function send(text){const i=$('#messageInput');if(!i)return;i.value=text;i.dispatchEvent(new Event('input',{bubbles:true}));i.focus();$('#composer')?.requestSubmit()}
function tab(name){$$('[data-tab]').find(x=>String(x.dataset.tab||'').toLowerCase()===name)?.click()}
function integrationsCount(v){if(!v)return 0;return[v.github?.configured,v.n8n?.configured,(v.shopify?.direct_configured||v.shopify?.automation_bridge),v.claude?.configured,v.railway?.running].filter(Boolean).length}
function createCard(list){const card=document.createElement('section');card.className='atlas-home-summary';card.dataset.project=project();card.innerHTML='<header><span class="atlas-home-mark">A</span><div><small>ATLAS · PROJECT HOME</small><h2></h2><p class="atlas-home-status">Собираю состояние проекта…</p></div></header><div class="atlas-home-stats"><button type="button" data-home="tasks"><span>Задачи</span><strong>…</strong><small>история проекта</small></button><button type="button" data-home="files"><span>Файлы</span><strong>…</strong><small>рабочие материалы</small></button><button type="button" data-home="auto"><span>Автоматизации</span><strong>…</strong><small>расписания</small></button><button type="button" data-home="integrations"><span>Интеграции</span><strong>…</strong><small>доступно</small></button></div><div class="atlas-home-recent hidden"><span>Последняя работа</span><strong></strong><small></small></div><footer><button type="button" class="primary" data-home="continue">Продолжить работу</button><button type="button" data-home="summary">Сводка проекта</button><button type="button" data-home="files">Файлы</button></footer>';card.querySelector('h2').textContent=projectName();card.addEventListener('click',e=>{const a=e.target.closest('[data-home]')?.dataset.home;if(!a)return;if(a==='files')tab('files');else if(a==='integrations')window.AtlasIntegrations?.open?.()||tab('plugins');else if(a==='auto')tab('auto');else if(a==='tasks')send('Покажи последние задачи текущего проекта, их статус и что сейчас важнее всего. Используй реальные данные проекта.');else if(a==='summary')send('Дай краткую актуальную сводку текущего проекта по реальным данным: готово, в работе, риски и следующий шаг.');else if(a==='continue')send('Проверь текущее состояние проекта и продолжи самый полезный безопасный следующий шаг. Сначала используй реальные данные проекта.')});list.prepend(card);return card}
function render(card,data){const jobs=jobsOf(data.history),files=filesOf(data.files),schedules=schedulesOf(data.schedules),done=jobs.filter(j=>state(j.status)==='done').length,working=jobs.filter(j=>state(j.status)==='working').length,bad=jobs.filter(j=>state(j.status)==='bad').length,ints=integrationsCount(data.integrations);const set=(name,value)=>{const b=card.querySelector(`[data-home="${name}"] strong`);if(b)b.textContent=value};set('tasks',jobs.length);set('files',files.length);set('auto',schedules.length);set('integrations',ints+'/5');const status=$('.atlas-home-status',card);if(status){if(working)status.textContent=`${working} ${working===1?'задача выполняется':'задачи выполняются'} · готово ${done}`;else if(bad)status.textContent=`Есть ${bad} ${bad===1?'ошибка':'ошибки'} для проверки · готово ${done}`;else if(jobs.length)status.textContent=`Готово ${done} из ${jobs.length} задач · можно переходить к следующему шагу`;else status.textContent='Проект готов к работе. Atlas может начать с аудита, плана или конкретной задачи.'}const recent=jobs.slice().sort((a,b)=>String(b.created_at||'').localeCompare(String(a.created_at||'')))[0],box=$('.atlas-home-recent',card);if(recent&&box){box.classList.remove('hidden');$('strong',box).textContent=String(recent.task||'Последняя задача').slice(0,110);$('small',box).textContent=state(recent.status)==='done'?'Завершено':state(recent.status)==='working'?'В работе':state(recent.status)==='bad'?'Нужна проверка':'В плане'}else box?.classList.add('hidden');card.dataset.loaded='1'}
async function hydrate(card){if(loading||!card)return;loading=true;const id=project(),q=encodeURIComponent(id);try{const settled=await Promise.allSettled([get('/app-projects/'+q+'/history'),get('/app-files?project_id='+q),get('/app-schedules?project_id='+q),get('/app-integrations/status')]);const pick=i=>settled[i].status==='fulfilled'?settled[i].value:null;render(card,{history:pick(0),files:pick(1),schedules:pick(2),integrations:pick(3)})}finally{loading=false}}
function syncMode(card,list){if(!card||!list)return;const old=$('.empty',list);const hasMessages=$$('.row.user,.row.assistant',list).length>0;card.classList.toggle('compact',hasMessages);if(old)old.classList.toggle('atlas-home-empty',true)}
function install(){const list=$('#chatList');if(!list)return;let existing=$('.atlas-home-summary',list),id=project();if(existing&&existing.dataset.project!==id){existing.remove();existing=null}if(!existing)existing=createCard(list);syncMode(existing,list);if(existing.dataset.loaded!=='1')hydrate(existing)}
new MutationObserver(install).observe(document.documentElement,{childList:true,subtree:true});
document.addEventListener('change',e=>{if(e.target?.id==='projectSelect')setTimeout(install,50)});
window.addEventListener('pageshow',install);
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',install,{once:true}):install();
window.AtlasHomeSummary={refresh:()=>{const c=$('.atlas-home-summary');if(c){c.dataset.loaded='0';hydrate(c)}else install()}};
})();