(()=>{'use strict';
const loaded=new Map(),pending=new Map();
const groups={
 tools:{js:['/app/tools-center.js'],css:['/app/tools-center.css']},
 templates:{js:['/app/templates-center.js'],css:['/app/templates-center.css']},
 integrations:{js:['/app/integrations-center.js'],css:['/app/integrations-center.css']},
 settings:{js:['/app/settings-center.js'],css:['/app/settings-center.css']},
 search:{js:['/app/project-search.js'],css:['/app/project-search.css']},
 share:{js:['/app/share-center.js'],css:['/app/share-center.css']},
 files:{js:['/app/files.js','/app/studio-panels.js','/app/studio-viewers.js','/app/studio-results.js','/app/file-studio-live.js'],css:['/app/studio-panels.css','/app/studio-viewers.css','/app/studio-results.css','/app/file-studio-live.css']},
 code:{js:['/app/studio-panels.js','/app/studio-viewers.js','/app/studio-results.js','/app/code-studio-live.js'],css:['/app/studio-panels.css','/app/studio-viewers.css','/app/studio-results.css','/app/code-studio-live.css']},
 video:{js:['/app/studio-panels.js','/app/studio-viewers.js','/app/studio-results.js','/app/video-studio-live.js'],css:['/app/studio-panels.css','/app/studio-viewers.css','/app/studio-results.css','/app/video-studio-live.css']},
 shopify:{js:['/app/studio-panels.js','/app/studio-viewers.js','/app/studio-results.js','/app/shopify-studio-live.js'],css:['/app/studio-panels.css','/app/studio-viewers.css','/app/studio-results.css','/app/shopify-studio-live.css']},
 automation:{js:['/app/schedules.js','/app/studio-panels.js','/app/studio-viewers.js','/app/studio-results.js','/app/automation-studio-live.js','/app/automation-executions.js'],css:['/app/schedules.css','/app/studio-panels.css','/app/studio-viewers.css','/app/studio-results.css','/app/automation-studio-live.css','/app/automation-executions.css']},
 workspace:{js:['/app/workspace-control.js'],css:['/app/workspace-control.css']},
 support:{js:['/app/recovery.js','/app/push.js','/app/control_center.js'],css:[]}
};
function enableStyle(path){for(const link of document.querySelectorAll('link[rel="stylesheet"]')){const lazyPath=link.getAttribute('data-atlas-href')||'';let p='';try{p=link.getAttribute('href')?new URL(link.href,location.href).pathname:''}catch{}if(lazyPath===path||p===path){if(!link.getAttribute('href'))link.setAttribute('href',path+'?lazy=20260827e');link.media='all';link.removeAttribute('data-atlas-lazy-style');return}}}
function existing(src){return [...document.scripts].some(s=>s.src&&new URL(s.src,location.href).pathname===src&&s.type!=='application/atlas-lazy')}
function loadScript(src){if(existing(src))return Promise.resolve();if(loaded.has(src))return loaded.get(src);let s;const p=new Promise((resolve,reject)=>{s=document.createElement('script');s.src=src+'?lazy=20260827e';s.defer=true;s.dataset.atlasLoaded='1';s.onload=resolve;s.onerror=()=>reject(new Error('Не удалось загрузить '+src));document.head.appendChild(s)}).catch(err=>{loaded.delete(src);try{s?.remove()}catch{}throw err});loaded.set(src,p);return p}
async function loadGroup(name){if(pending.has(name))return pending.get(name);const p=(async()=>{const g=groups[name]||{js:[],css:[]};for(const css of g.css)enableStyle(css);for(const src of g.js)await loadScript(src);return true})();pending.set(name,p);try{return await p}finally{pending.delete(name)}}
function labelOf(target){const nav=target.closest?.('.ref-nav-item');if(nav)return nav.textContent.trim();const card=target.closest?.('.dash-tool-card,.atlas-tool-live-card,.atlas-template-card,.atlas-action-card');if(card)return card.textContent.trim();return target.textContent?.trim?.()||''}
function groupFromLabel(text){const t=String(text||'').toLowerCase();if(t.includes('code studio')||t.includes('code review')||t.includes('bug fix'))return'code';if(t.includes('video studio')||t.includes('ugc')||t.includes('reels')||t.includes('tiktok'))return'video';if(t.includes('shopify studio')||t.includes('product page')||t.includes('cro'))return'shopify';if(t.includes('file studio')||t==='файлы'||t.includes('анализ файла'))return'files';if(t.includes('automation studio')||t.includes('n8n'))return'automation';return''}
function openCenter(name){const api={tools:'AtlasToolsCenter',templates:'AtlasTemplatesCenter',integrations:'AtlasIntegrationsCenter',settings:'AtlasSettingsCenter',search:'AtlasProjectSearch',share:'AtlasShareCenter'}[name];const obj=api&&window[api];if(obj?.open){obj.open();return true}return false}
async function handleFeatureClick(e){if(e.__atlasLazyReplay)return;const target=e.target,text=labelOf(target);let center='';if(text==='Инструменты'||target.closest?.('.dash-tool-card.add'))center='tools';else if(text==='Шаблоны')center='templates';else if(text==='Интеграции')center='integrations';else if(text==='Настройки'||target.closest?.('#settingsBtn'))center='settings';else if(/^поделиться$/i.test(text)||target.closest?.('[data-action="share"]'))center='share';if(center){e.preventDefault();e.stopImmediatePropagation();try{await loadGroup(center);openCenter(center)}catch(err){console.error(err);window.AtlasClientTelemetry?.report?.({kind:'lazy.center',message:String(err&&err.message||err),source:center,line:'',column:'',stack:String(err&&err.stack||'')})}return}const feature=groupFromLabel(text);if(feature){const card=target.closest?.('.dash-tool-card,.atlas-tool-live-card,.atlas-template-card,.atlas-action-card,.ref-nav-item')||target;e.preventDefault();e.stopImmediatePropagation();try{await loadGroup(feature);const replay=new MouseEvent('click',{bubbles:true,cancelable:true,view:window});Object.defineProperty(replay,'__atlasLazyReplay',{value:true});card.dispatchEvent(replay)}catch(err){console.error(err);window.AtlasClientTelemetry?.report?.({kind:'lazy.feature',message:String(err&&err.message||err),source:feature,line:'',column:'',stack:String(err&&err.stack||'')})}}}
window.addEventListener('click',e=>void handleFeatureClick(e),true);
window.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&String(e.key).toLowerCase()==='k'&&!window.AtlasProjectSearch?.open){e.preventDefault();void loadGroup('search').then(()=>window.AtlasProjectSearch?.open?.())}},true);
setTimeout(()=>void loadGroup('support'),7000);
window.AtlasLazy={loadGroup,loadScript,enableStyle,groups};
})();