(()=>{'use strict';
const BUILD='atlas-runtime-stable-20260827e';
let healthTimer=0,cleanupStarted=false,guardCard=null,guardObserver=null,resumeGeneration=0;
const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function bounded(promise,ms=1800){try{return await Promise.race([Promise.resolve(promise),delay(ms).then(()=>null)])}catch{return null}}
function paint(online){const s=document.getElementById('serviceStatus');if(s)s.textContent=online?'online':'offline';const dot=document.querySelector('.topbar .dot');if(dot){dot.classList.toggle('online',online);dot.classList.toggle('offline',!online)}try{window.dispatchEvent(new CustomEvent('atlas-brand-health',{detail:{online,source:'runtime-refresh'}}))}catch{}}
async function health(){try{const r=await fetch('/health?atlas_refresh='+Date.now(),{cache:'no-store',credentials:'same-origin',headers:{'Cache-Control':'no-cache'}});paint(r.ok);return r.ok}catch{paint(false);return false}}
async function session(){try{const r=await fetch('/app-session?atlas_boot='+Date.now(),{cache:'no-store',credentials:'same-origin',headers:{'Cache-Control':'no-cache'}});if(!r.ok)return false;const j=await r.json();return j?.authenticated===true}catch{return false}}
async function removeAtlasWorkers(){if(cleanupStarted||!('serviceWorker'in navigator))return;cleanupStarted=true;try{const regs=await bounded(navigator.serviceWorker.getRegistrations());if(Array.isArray(regs)){await bounded(Promise.allSettled(regs.map(async reg=>{const urls=[reg.active?.scriptURL,reg.waiting?.scriptURL,reg.installing?.scriptURL].filter(Boolean).join(' ');if(urls.includes('/app/sw.js'))await reg.unregister()})))}try{const keys=await bounded(caches.keys());if(Array.isArray(keys))await bounded(Promise.allSettled(keys.filter(k=>k.startsWith('atlas-app-')).map(k=>caches.delete(k))))}catch{}}catch{}}
function installLoginGuard(){const card=document.getElementById('loginCard');if(!card)return;const input=document.getElementById('passwordInput');const sync=()=>{const open=!card.classList.contains('hidden');document.body.classList.toggle('atlas-login-open',open)};if(guardCard!==card){try{guardObserver?.disconnect()}catch{}guardCard=card;try{guardObserver=new MutationObserver(sync);guardObserver.observe(card,{attributes:true,attributeFilter:['class']})}catch{guardObserver=null}if(input&&!input.dataset.atlasLoginGuard){input.dataset.atlasLoginGuard='1';const refocus=()=>setTimeout(()=>{try{input.focus({preventScroll:false})}catch{try{input.focus()}catch{}}},0);input.addEventListener('touchend',refocus,{passive:true});input.addEventListener('pointerup',refocus,{passive:true})}}sync()}
function coreVisible(){const login=document.getElementById('loginCard'),chat=document.getElementById('chatCard'),composer=document.getElementById('composerWrap');return !!(login?.classList.contains('hidden')&&chat&&!chat.classList.contains('hidden')&&composer&&!composer.classList.contains('hidden'))}
function revealCore(){const login=document.getElementById('loginCard'),chat=document.getElementById('chatCard'),composer=document.getElementById('composerWrap');login?.classList.add('hidden');chat?.classList.remove('hidden');composer?.classList.remove('hidden');document.body.classList.remove('atlas-login-open');document.body.classList.add('atlas-core-ready');paint(true);try{window.dispatchEvent(new CustomEvent('atlas-core-fallback',{detail:{build:BUILD}}))}catch{}}
async function failSoftBoot(authenticated){const ok=authenticated===true?true:await session();if(!ok)return;setTimeout(()=>{if(!coreVisible())revealCore()},500);setTimeout(()=>{if(!coreVisible())revealCore()},1800)}
function stopHealthLoop(){if(healthTimer){clearInterval(healthTimer);healthTimer=0}}
function startHealthLoop(){if(document.hidden||healthTimer)return;healthTimer=setInterval(()=>{if(!document.hidden)void health()},15000)}
async function resume(source='resume'){const generation=++resumeGeneration;installLoginGuard();startHealthLoop();const [online,authenticated]=await Promise.all([health(),session()]);if(generation!==resumeGeneration)return;if(authenticated)await failSoftBoot(true);try{window.dispatchEvent(new CustomEvent('atlas-runtime-resume',{detail:{source,online,authenticated,build:BUILD}}))}catch{}}
function boot(){installLoginGuard();startHealthLoop();void resume('boot');window.addEventListener('online',()=>void resume('online'));window.addEventListener('offline',()=>paint(false));window.addEventListener('pagehide',()=>{stopHealthLoop()});window.addEventListener('pageshow',event=>{void resume(event.persisted?'pageshow-bfcache':'pageshow')});document.addEventListener('visibilitychange',()=>{if(document.hidden){stopHealthLoop();return}void resume('visible')})}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot,{once:true}):boot();
// Worker cleanup is deliberately manual-only. Removing a controlling worker/cache
// during normal Safari boot or resume can restart the document on iPadOS.
window.AtlasRuntimeRefresh={health,session,installLoginGuard,removeAtlasWorkers,revealCore,resume,build:BUILD};
})();