(()=>{'use strict';
const BUILD='atlas-runtime-stable-20260827b';
function paint(online){const s=document.getElementById('serviceStatus');if(s)s.textContent=online?'online':'offline';const dot=document.querySelector('.topbar .dot');if(dot){dot.classList.toggle('online',online);dot.classList.toggle('offline',!online)}try{window.dispatchEvent(new CustomEvent('atlas-brand-health',{detail:{online,source:'runtime-refresh'}}))}catch{}}
async function health(){try{const r=await fetch('/health?atlas_refresh='+Date.now(),{cache:'no-store',credentials:'same-origin',headers:{'Cache-Control':'no-cache'}});paint(r.ok);return r.ok}catch{paint(false);return false}}
async function removeAtlasWorkers(){if(!('serviceWorker'in navigator))return;try{const regs=await navigator.serviceWorker.getRegistrations();await Promise.allSettled(regs.map(async reg=>{const urls=[reg.active?.scriptURL,reg.waiting?.scriptURL,reg.installing?.scriptURL].filter(Boolean).join(' ');if(urls.includes('/app/sw.js'))await reg.unregister()}))}catch{}}
function installLoginGuard(){const card=document.getElementById('loginCard');if(!card)return;const input=document.getElementById('passwordInput');const sync=()=>{const open=!card.classList.contains('hidden');document.body.classList.toggle('atlas-login-open',open)};try{new MutationObserver(sync).observe(card,{attributes:true,attributeFilter:['class']})}catch{}if(input){const refocus=()=>setTimeout(()=>{try{input.focus({preventScroll:false})}catch{try{input.focus()}catch{}}},0);input.addEventListener('touchend',refocus,{passive:true});input.addEventListener('pointerup',refocus,{passive:true})}sync()}
function boot(){installLoginGuard();void health();void removeAtlasWorkers();setInterval(()=>void health(),15000);window.addEventListener('online',()=>void health());window.addEventListener('offline',()=>paint(false));window.addEventListener('pageshow',()=>{installLoginGuard();void health();void removeAtlasWorkers()});document.addEventListener('visibilitychange',()=>{if(!document.hidden){installLoginGuard();void health()}})}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot,{once:true}):boot();
window.AtlasRuntimeRefresh={health,installLoginGuard,removeAtlasWorkers,build:BUILD};
})();