(()=>{'use strict';
const BUILD='atlas-runtime-stable-20260827c';
function paint(online){const s=document.getElementById('serviceStatus');if(s)s.textContent=online?'online':'offline';const dot=document.querySelector('.topbar .dot');if(dot){dot.classList.toggle('online',online);dot.classList.toggle('offline',!online)}try{window.dispatchEvent(new CustomEvent('atlas-brand-health',{detail:{online,source:'runtime-refresh'}}))}catch{}}
async function health(){try{const r=await fetch('/health?atlas_refresh='+Date.now(),{cache:'no-store',credentials:'same-origin',headers:{'Cache-Control':'no-cache'}});paint(r.ok);return r.ok}catch{paint(false);return false}}
async function session(){try{const r=await fetch('/app-session?atlas_boot='+Date.now(),{cache:'no-store',credentials:'same-origin',headers:{'Cache-Control':'no-cache'}});if(!r.ok)return false;const j=await r.json();return j?.authenticated===true}catch{return false}}
async function removeAtlasWorkers(){if(!('serviceWorker'in navigator))return;try{const regs=await navigator.serviceWorker.getRegistrations();await Promise.allSettled(regs.map(async reg=>{const urls=[reg.active?.scriptURL,reg.waiting?.scriptURL,reg.installing?.scriptURL].filter(Boolean).join(' ');if(urls.includes('/app/sw.js'))await reg.unregister()}));try{const keys=await caches.keys();await Promise.allSettled(keys.filter(k=>k.startsWith('atlas-app-')).map(k=>caches.delete(k)))}catch{}}catch{}}
function installLoginGuard(){const card=document.getElementById('loginCard');if(!card)return;const input=document.getElementById('passwordInput');const sync=()=>{const open=!card.classList.contains('hidden');document.body.classList.toggle('atlas-login-open',open)};try{new MutationObserver(sync).observe(card,{attributes:true,attributeFilter:['class']})}catch{}if(input){const refocus=()=>setTimeout(()=>{try{input.focus({preventScroll:false})}catch{try{input.focus()}catch{}}},0);input.addEventListener('touchend',refocus,{passive:true});input.addEventListener('pointerup',refocus,{passive:true})}sync()}
function coreVisible(){const login=document.getElementById('loginCard'),chat=document.getElementById('chatCard'),composer=document.getElementById('composerWrap');return !!(login?.classList.contains('hidden')&&chat&&!chat.classList.contains('hidden')&&composer&&!composer.classList.contains('hidden'))}
function revealCore(){const login=document.getElementById('loginCard'),chat=document.getElementById('chatCard'),composer=document.getElementById('composerWrap');login?.classList.add('hidden');chat?.classList.remove('hidden');composer?.classList.remove('hidden');document.body.classList.remove('atlas-login-open');document.body.classList.add('atlas-core-ready');paint(true);try{window.dispatchEvent(new CustomEvent('atlas-core-fallback',{detail:{build:BUILD}}))}catch{}}
async function failSoftBoot(){const ok=await session();if(!ok)return;setTimeout(()=>{if(!coreVisible())revealCore()},1200);setTimeout(()=>{if(!coreVisible())revealCore()},3200)}
function boot(){installLoginGuard();void health();void removeAtlasWorkers();void failSoftBoot();setInterval(()=>void health(),15000);window.addEventListener('online',()=>void health());window.addEventListener('offline',()=>paint(false));window.addEventListener('pageshow',()=>{installLoginGuard();void health();void removeAtlasWorkers();void failSoftBoot()});document.addEventListener('visibilitychange',()=>{if(!document.hidden){installLoginGuard();void health()}})}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot,{once:true}):boot();
window.AtlasRuntimeRefresh={health,session,installLoginGuard,removeAtlasWorkers,revealCore,build:BUILD};
})();