(()=>{'use strict';
const $=id=>document.getElementById(id);
const E={dot:$('dot'),status:$('status'),project:$('project'),chat:$('chat'),form:$('composer'),input:$('message'),send:$('send'),notice:$('notice'),newChat:$('newChat'),full:$('fullAtlas')};
let projectId='project-general',responseId='',activeJob='',busy=false,history=[];
const key=suffix=>`atlas_safe_${suffix}::${projectId}`;
const save=()=>{try{localStorage.setItem(key('history'),JSON.stringify(history.slice(-100)));responseId?localStorage.setItem(key('rid'),responseId):localStorage.removeItem(key('rid'));activeJob?localStorage.setItem(key('job'),activeJob):localStorage.removeItem(key('job'))}catch{}};
const load=()=>{try{history=JSON.parse(localStorage.getItem(key('history'))||'[]')||[]}catch{history=[]}try{responseId=localStorage.getItem(key('rid'))||'';activeJob=localStorage.getItem(key('job'))||''}catch{responseId='';activeJob=''}render()};
const notify=(text='',kind='')=>{E.notice.textContent=text;E.notice.classList.toggle('show',!!text);E.notice.dataset.kind=kind};
const setOnline=on=>{E.dot.classList.toggle('on',!!on);E.status.textContent=on?'online':'offline'};
const scroll=()=>{const main=document.querySelector('.main');if(main)main.scrollTop=main.scrollHeight};
function render(){E.chat.textContent='';if(!history.length){E.chat.innerHTML='<div class="empty"><div class="a">A</div><h1>Atlas Safe Mode</h1><p>Рабочий чат без тяжёлого интерфейса. Использует тот же backend и проекты Atlas.</p></div>';return}for(const m of history){const r=document.createElement('div');r.className='row '+(m.role==='user'?'user':'assistant');const b=document.createElement('div');b.className='bubble';b.textContent=m.text||'';r.appendChild(b);E.chat.appendChild(r)}scroll()}
const push=(role,text)=>{history.push({role,text});save();render()};
const setBusy=(on,label='')=>{busy=!!on;E.send.disabled=busy;E.input.disabled=busy;if(label)notify(label,'progress')};
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function checkSession(){try{const r=await fetch('/app-session?safe='+Date.now(),{cache:'no-store',credentials:'same-origin'});const j=await r.json();if(!j.authenticated){location.replace('/app/login.html?v='+Date.now());return false}return true}catch{notify('Нет соединения с Atlas','error');return false}}
async function loadProjects(){try{const r=await fetch('/app-projects',{cache:'no-store',credentials:'same-origin'});if(r.status===401){location.replace('/app/login.html?v='+Date.now());return}if(!r.ok)throw new Error('HTTP '+r.status);const j=await r.json();const projects=Array.isArray(j.projects)?j.projects:[];E.project.textContent='';for(const p of projects){const o=document.createElement('option');o.value=p.id;o.textContent=p.name||p.id;E.project.appendChild(o)}let preferred='';try{preferred=localStorage.getItem('atlas_active_project_id')||''}catch{}if(preferred&&projects.some(p=>p.id===preferred))projectId=preferred;else if(projects[0])projectId=projects[0].id;E.project.value=projectId;load();notify('')}catch(e){notify('Не удалось загрузить проекты: '+(e?.message||'ошибка'),'error')}}
async function health(){try{const r=await fetch('/health?safe='+Date.now(),{cache:'no-store'});setOnline(r.ok)}catch{setOnline(false)}}
async function poll(jobId){setBusy(true,'Atlas думает…');const started=Date.now();try{while(activeJob===jobId){if(Date.now()-started>5*60*1000)throw new Error('Задача выполняется слишком долго. Попробуйте открыть её позже.');const r=await fetch('/app-jobs/'+encodeURIComponent(jobId)+'?safe='+Date.now(),{cache:'no-store',credentials:'same-origin'});if(r.status===401){location.replace('/app/login.html?v='+Date.now());return}const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.detail||j.error||('HTTP '+r.status));if(j.status==='done'){responseId=j.response_id||responseId;activeJob='';push('assistant',String(j.answer||'Готово.'));notify('Готово','ok');return}if(j.status==='error')throw new Error(j.error||'Ошибка Atlas');if(j.status==='cancelled'){activeJob='';push('assistant','Задача остановлена.');notify('Задача остановлена','error');return}await wait(1200)}}catch(e){activeJob='';const msg=e?.message||'Ошибка Atlas';push('assistant',msg);notify(msg,'error')}finally{setBusy(false);save()}}
async function send(){const text=(E.input.value||'').trim();if(!text||busy)return;notify('Отправляю…','progress');push('user',text);E.input.value='';setBusy(true,'Отправляю…');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);try{const r=await fetch('/app-jobs',{method:'POST',credentials:'same-origin',cache:'no-store',signal:controller.signal,headers:{'Content-Type':'application/json','Cache-Control':'no-cache'},body:JSON.stringify({task:text,previous_response_id:responseId||null,project_id:projectId,allow_writes:false,claude_review:false,attachments:[]})});clearTimeout(timer);if(r.status===401){location.replace('/app/login.html?v='+Date.now());return}const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.detail||j.error||('HTTP '+r.status));if(!j.job_id)throw new Error('Atlas не вернул ID задачи');activeJob=j.job_id;save();await poll(activeJob)}catch(e){clearTimeout(timer);const msg=e?.name==='AbortError'?'Atlas не ответил за 20 секунд':(e?.message||'Ошибка Atlas');push('assistant',msg);notify(msg,'error');setBusy(false)}}
E.form.addEventListener('submit',e=>{e.preventDefault();void send()});
E.input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send()}});
E.project.addEventListener('change',()=>{save();projectId=E.project.value||'project-general';try{localStorage.setItem('atlas_active_project_id',projectId)}catch{}load();if(activeJob)void poll(activeJob)});
E.newChat.addEventListener('click',()=>{history=[];responseId='';activeJob='';save();render();notify('Новый чат создан','ok');E.input.focus()});
E.full.addEventListener('click',()=>location.assign('/?stable=1&from=safe&t='+Date.now()));
(async()=>{if(!await checkSession())return;await health();await loadProjects();if(activeJob)void poll(activeJob);setInterval(health,15000);setTimeout(()=>E.input.focus(),250)})();
})();