(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const ACTIVE='atlas_active_project_id';
let overlay=null,previousFocus=null;
function projectId(){try{return localStorage.getItem(ACTIVE)||'project-general'}catch{return'project-general'}}
function projectName(){return $('#projectSelect')?.selectedOptions?.[0]?.textContent?.trim()||$('.atlas-project-name')?.textContent?.trim()||'Atlas project'}
function deepLink(){const u=new URL(location.pathname,location.origin);u.searchParams.set('project',projectId());return u.toString()}
async function get(url){const r=await fetch(url,{credentials:'same-origin',cache:'no-store'}),j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.detail||j.error||`HTTP ${r.status}`);return j}
async function copy(text){try{await navigator.clipboard.writeText(text);return true}catch{}const t=document.createElement('textarea');t.value=text;t.setAttribute('readonly','');t.style.position='fixed';t.style.opacity='0';document.body.append(t);t.select();let ok=false;try{ok=document.execCommand('copy')}catch{}t.remove();return ok}
function close(){if(!overlay)return;overlay.remove();overlay=null;document.body.classList.remove('atlas-share-open');const f=previousFocus;previousFocus=null;try{f?.focus?.({preventScroll:true})}catch{}}
function toast(text,bad=false){if(!overlay)return;const n=$('.atlas-share-toast',overlay);n.textContent=text;n.classList.toggle('bad',bad);n.classList.add('show');setTimeout(()=>n?.classList.remove('show'),1700)}
function jobsOf(v){return Array.isArray(v?.history)?v.history:Array.isArray(v?.jobs)?v.jobs:[]}
function filesOf(v){return Array.isArray(v)?v:Array.isArray(v?.files)?v.files:[]}
function schedulesOf(v){return Array.isArray(v)?v:Array.isArray(v?.schedules)?v.schedules:[]}
function statusKind(s){s=String(s||'').toLowerCase();if(['done','success','completed'].includes(s))return'done';if(['running','queued','pending','working'].includes(s))return'working';if(['failed','error','cancelled'].includes(s))return'bad';return'plan'}
function integrationsCount(v){return [v?.github?.configured,v?.n8n?.configured,(v?.shopify?.direct_configured||v?.shopify?.automation_bridge),v?.claude?.configured,v?.railway?.running].filter(Boolean).length}
async function projectBrief(){const id=encodeURIComponent(projectId());const settled=await Promise.allSettled([get('/app-projects/'+id+'/history'),get('/app-files?project_id='+id),get('/app-schedules?project_id='+id),get('/app-integrations/status')]);const pick=i=>settled[i].status==='fulfilled'?settled[i].value:null,jobs=jobsOf(pick(0)),files=filesOf(pick(1)),schedules=schedulesOf(pick(2)),ints=integrationsCount(pick(3));const done=jobs.filter(x=>statusKind(x.status)==='done').length,working=jobs.filter(x=>statusKind(x.status)==='working').length,bad=jobs.filter(x=>statusKind(x.status)==='bad').length,recent=jobs.slice().sort((a,b)=>String(b.created_at||'').localeCompare(String(a.created_at||'')))[0];const lines=[`Atlas · ${projectName()}`,`Задачи: ${done} готово · ${working} в работе · ${bad} ошибок · ${jobs.length} всего`,`Файлы: ${files.length}`,`Автоматизации: ${schedules.length}`,`Интеграции: ${ints}/5`];if(recent?.task)lines.push('Последняя работа: '+String(recent.task).replace(/\s+/g,' ').trim().slice(0,180));lines.push('Ссылка: '+deepLink());return lines.join('\n')}
function action(icon,title,desc,fn){const b=document.createElement('button');b.type='button';b.className='atlas-share-action';b.innerHTML='<span class="atlas-share-icon"></span><span><strong></strong><small></small></span><b>→</b>';b.querySelector('.atlas-share-icon').textContent=icon;b.querySelector('strong').textContent=title;b.querySelector('small').textContent=desc;b.onclick=fn;return b}
async function nativeShare(){const data={title:'Atlas · '+projectName(),text:'Рабочий проект Atlas: '+projectName(),url:deepLink()};if(navigator.share){try{await navigator.share(data);toast('Открыто системное меню Share');return}catch(e){if(e?.name==='AbortError')return}}const ok=await copy(data.url);toast(ok?'Ссылка скопирована':'Не удалось скопировать',!ok)}
async function copyLink(){const ok=await copy(deepLink());toast(ok?'Ссылка проекта скопирована':'Не удалось скопировать',!ok)}
async function copyBrief(){const button=$('[data-share-brief]',overlay);if(button)button.disabled=true;try{const text=await projectBrief(),ok=await copy(text);toast(ok?'Сводка проекта скопирована':'Не удалось скопировать',!ok)}catch(e){toast(e.message||'Не удалось собрать сводку',true)}finally{if(button)button.disabled=false}}
function exportChat(){close();$('#exportChatBtn')?.click()}
function trap(e){if(!overlay)return;if(e.key==='Escape'){e.preventDefault();close();return}if(e.key!=='Tab')return;const list=$$('button,[href],[tabindex]:not([tabindex="-1"])',overlay).filter(x=>!x.disabled);if(!list.length){e.preventDefault();return}const first=list[0],last=list[list.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}
function open(){close();previousFocus=document.activeElement;overlay=document.createElement('div');overlay.className='atlas-share-overlay';overlay.innerHTML='<section class="atlas-share" role="dialog" aria-modal="true" aria-labelledby="atlas-share-title"><header><div><small>ATLAS · PROJECT SHARE</small><h2 id="atlas-share-title">Поделиться проектом</h2><p></p></div><button type="button" class="atlas-share-close" aria-label="Закрыть">×</button></header><div class="atlas-share-actions"></div><footer><span class="atlas-share-toast" aria-live="polite"></span><small>Ссылка открывает этот проект в Atlas, но не обходит вход и не раскрывает секреты.</small></footer></section>';$('.atlas-share header p',overlay).textContent=projectName();const host=$('.atlas-share-actions',overlay);const sys=action('↗','Системное Share','AirDrop, Messages, Mail и другие приложения',nativeShare),link=action('⌁','Скопировать ссылку','Deep-link на текущий Atlas project',copyLink),brief=action('≡','Скопировать сводку','Живые задачи, файлы, автоматизации и интеграции',copyBrief),exp=action('↓','Экспортировать чат','Сохранить текущую переписку локально',exportChat);brief.dataset.shareBrief='1';host.append(sys,link,brief,exp);overlay.addEventListener('click',e=>{if(e.target===overlay)close()});overlay.addEventListener('keydown',trap);$('.atlas-share-close',overlay).onclick=close;document.body.append(overlay);document.body.classList.add('atlas-share-open');requestAnimationFrame(()=>$('.atlas-share-close',overlay)?.focus());return overlay}
document.addEventListener('click',e=>{const b=e.target.closest?.('.dash-head-btn[data-control-icon="share"],.dash-head-btn[aria-label="Поделиться"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();open()},true);
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&overlay){e.preventDefault();close()}},true);
window.AtlasShare={open,close,deepLink,projectBrief};
})();